TEST_VALUE:
  name: cookie

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3ceb5013a38900e
  FEISHU_APP_SECRET: P4p1oLGoTLibuYYws1Q1ldp46myVFYKL

MONGODB_CONFIG:
  name: "devtest"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://192.168.3.170:27017"   # 数据库链接地址
  username: "devtest"                   # 数据库链接用户名
  password: "HCLcsEBNiKjRLffw"                 # 数据库链接密码
  database: "devtest"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能